apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlSb290UGFzc3dvcmQ=
  MYSQL_DATABASE: bXlEYXRhYmFzZQ==
  MYSQL_USER: bXlVc2Vy
  MYSQL_PASSWORD: bXlQYXNzd29yZA==

